[build]
  base = "/"
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"
  publish = "book"

[[redirects]]
  from = "https://rsapkf-links.netlify.app/*"
  to = "https://links.rsapkf.xyz/:splat"
  status = 301
  force = true
